### PR TITLE
First checkout

### PR DESCRIPTION
**Pull request by Lonartie**
As you can see I made some changes to the code.
Also, I don't understand why graphic assets and prefabs are inside of Scenes.

Feel free to criticize me and my changes so that we can exchange some experience during this project :)

### CODE REVIEW

**Comment by alinajm7** [comment]
Hi Man, thank you for your feedback and corrections.

Regarding the Github plugin, I didn't know. (Thanks for update)

for XML format, I agree, it is easier and more standardized this way  (I did manual format because in other projects I need a specific format and pattern which is not requested here)

**Comment by alinajm7** [comment]
I don't know how Leonie wants to collect the saved data.
Do you have any idea?

email, google form or server?

**Comment by Lonartie** [comment]
> I don't know how Leonie wants to collect the saved data.
> Do you have any idea?
> 
> email, google form or server?

I would suggest saving the data to a database. That's what they are made for :D
But the user has to keep their data locally as well because when they currently don't have internet access they wouldn't be able to play the game.

**Comment by Lonartie** [comment]
We could use a free bplaced.net server for now. They offer some Webspace, Email Traffic, PhpMyAdmin access etc.

Because when a database holds the collected data then Leonie could easily manipulate what data she wants and in which format.

**Comment by alinajm7** [comment]
Agree, we can use firebase.google.com also. (but whatever you are comfortable with it is fine for me.)
Let's ask her to be sure about how she wants the data and proceed.
If you agree you can proceed with the database and I will start coding for the game.
(1 step I will make the random path with her tiles)

**Comment by Lonartie** [comment]
I already asked her if it would be ok when we store the data inside a database. It's fine.
Ok then I will create a database and scripts for communication and you'll work on the path algorithm 👍🏻

Can this pull request be merged?

**Comment by alinajm7** [comment]
sorry for the delay. I just did it :)
Also, I will move the graphics (image) folder out of the scene folder. (I did it because of a habit from other projects in which I had a specific asset for each scene. in that case I found it more convinent )

**Pull request merged**
